### ISSUE TITLE
Add fallback if slug undefined

### ISSUE THREAD

**Issue by walutisme** [ducksoupdev/gulp-site-generator#1]
Can you add feature or maybe as a fallback if post slug are undefined then it takes post title and convert it to valid slug?
```
title: This is Title
```
Will be like this before compiled:
```
title: This is Title
slug: this-is-title
```

**Comment by ducksoupdev** [comment]
Thanks, that's a good feature,  I'll add it to the backlog. Unless you fancy doing a pull - request?

**Comment by ducksoupdev** [comment]
The feature is now in the latest version 0.1.13.
