### ISSUE TITLE
help with install steps in readme

### ISSUE THREAD

**Issue by chancesmith** [ducksoupdev/gulp-site-generator#15]
$ node tools/install

This didn't run for me. :/

**Comment by ducksoupdev** [comment]
Hi, can you post a screenshot or description of the error you are getting?

**Comment by chancesmith** [comment]
https://www.dropbox.com/s/ras5d9u2185vz05/Screenshot%202016-03-30%2015.54.26.png?dl=0

**Comment by ringods** [comment]
@chancesmith downloading the generator like you did doesn't work. The README contains this:

```
$ git submodule add https://github.com/ducksoupdev/gulp-site-generator.git tools
```

You run this command in the folder where you want to store your static site setup. Look at the end of the line, you retrieve the git repository and save it locally in the `tools` folder. Once you have this, then run `node tools/install`. Node will execute the `install.js` script in the tools folder.

Hope that makes the setup clear.
