### ISSUE TITLE
{{resolve "/path/to/href" }} helper prefixes "./" to all generated links 

### ISSUE THREAD

**Issue by bmcminn** [ducksoupdev/gulp-site-generator#19]
Testing this system out on Windows 7 Pro 64bit using Node 6.0.0.

For whatever reason, the default `{{resolve }}` helper in `gulp-site-generator` is taking the default markup contents and prefixing their `href` contents with `./`...

``` hbs
<!-- partials/header.hbs -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{meta_description}}">
    <meta name="author" content="">
    <link rel="icon" href="{{resolve "/favicon.ico"}}">
    <title>{{meta_title}}</title>
    <link rel="stylesheet" type="text/css" href="{{resolve "/css/style.min.css"}}">
    <meta name="generator" content="{{generator}}" />
    <link rel="alternate" type="application/rss+xml" title="{{site.title}}" href="{{rss}}">
</head>

<body>
```

``` html
<!-- resulting markup -->
<!DOCTYPE html>
<html lang=en>
<head>
<meta charset=utf-8>
<meta http-equiv=X-UA-Compatible content="IE=edge">
<meta name=viewport content="width=device-width, initial-scale=1">
<meta name=description>
<meta name=author>
<link rel=icon href=./favicon.ico>
<title>
</title>
<link rel=stylesheet type=text/css href=./css/style.min.css>
<meta name=generator content="Gulp 3.9.1">
<link rel=alternate type=application/rss+xml href=./rss.xml>
</head>
<body>
```

These `./` prefixes cause Chrome to interpret these links in wierd ways, where each subsequent click appends the links `href` value to the end of the current page URL and redirects to that now non-existent route.

Did a cursory look into the `resolve` helper, and its implementation makes little sense to me... it seems this `resolvePaths` handler defined through the `tools/` files is using some seriously inconceivable routes (eg: `url: "../../../..",`...) when it would be prudent to use something like `process.cwd()` to construct a relative directory reference.

**Comment by ducksoupdev** [comment]
Hi, sorry for the delay in replying. I agree, that part of the code isn't great and needs refactoring. Using `process.cwd()` is a good idea - will look into that. Happy to accept a PR if you have a solution in mind?

**Comment by ducksoupdev** [comment]
Version 0.2 includes a fix for this issue. Can you update your submodule to the latest (v0.2.1 - https://github.com/ducksoupdev/gulp-site-generator/tree/v0.2.1) and try it?
