### ISSUE TITLE
uncss returns an empty css file

### ISSUE THREAD

**Issue by ringods** [ducksoupdev/gulp-site-generator#23]
sass to css conversion works fine, but running uncss results in an empty css file. There are a lot of CSS classifiers which _are_ used in my HTML files, so these should remain in the final css file.

**Comment by ducksoupdev** [comment]
I have a branch with a change to the uncss task that checks for an optional config in `./site.json` to specify selectors to leave untouched. I should be able to merge shortly.

**Comment by ducksoupdev** [comment]
Apologies for the delay, things have been busy! I have merged the uncss ignore change to v0.1.29
