### ISSUE TITLE
Adding watch, server, and livereload tasks in default task of gulp.

### ISSUE THREAD

**Issue by implict** [ducksoupdev/gulp-site-generator#3]
Hi, I tried to add watch, server, and livereload tasks in default task.
However, it does not work well.
Could you tell me the way?

**Comment by ducksoupdev** [comment]
Hi, thanks for prompting me! There is a **develop** task (run `gulp develop`) that should watch for changes to the src directory and automatically run the default task. There was an issue with it but that has now been resolved. Run the develop task from your site and it should live reload and build the site whenever changes are detected.
