### ISSUE TITLE
Error when running default gulp task after install

### ISSUE THREAD

**Issue by alexrdz** [ducksoupdev/gulp-site-generator#33]
After installing and running `gulp` for the first time, I get the following error:
```
TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/alexrodriguez/Sites/_practice/qwe/node_modules/require-dir/index.js:97:37)
```
I updated the `require-dir` npm package to `"require-dir": "^0.3.2"` and everything worked perfectly. (I am running node version v8.1.3).

**Comment by ducksoupdev** [comment]
Thanks for letting me know @alexrdz. I have created an issue to look at Node 8.x compatibility and will ensure this is looked at. See #34.

**Comment by ducksoupdev** [comment]
Release [v0.4.1](https://github.com/ducksoupdev/gulp-site-generator/tree/v0.4.1) has been tested with Node v8.1.4 and is compatible.
