### ISSUE TITLE
New property declared in site.json isn't available.

### ISSUE THREAD

**Issue by tibor-kulcar** [ducksoupdev/gulp-site-generator#5]
When i try to add new propety in site.json file, i am not able to reach it in handlebars template.

**Comment by ducksoupdev** [comment]
Properties in the site.json file are available in the handlebars templates at the top level. For example {{site.title}}. Where in the template are you trying to access the property?

**Comment by tibor-kulcar** [comment]
I've tried it in all templates. Right now I returned back to try it again and it was in templates/partials/loop.hbs.

**Comment by ducksoupdev** [comment]
The latest release https://github.com/ducksoupdev/gulp-site-generator/tree/v0.1.20 had an update for adding site data to individual pages/posts. Have you updated the generator and managed to use your new properties in your templates?
