### ISSUE TITLE
Error: The partial pagination could not be found

### ISSUE THREAD

**Issue by neilberry** [ducksoupdev/gulp-site-generator#6]
Hi Matt,

Tried this out this evening, but when running "gulp" I get this message: 

Error: The partial pagination could not be found.

Am I missing something?

![image](https://cloud.githubusercontent.com/assets/1056228/11671200/67aba3ac-9dfe-11e5-89fb-344e78af0be0.png)

Thanks,
Neil

**Comment by ducksoupdev** [comment]
Hi Neil,

Apologies, I should have added this to the CHANGELOG. As there is a new file and you have already run the install script, you'll need to manually copy the partial to your project.

The partial needs to be copied from `tools/install/templates/partials/pagination.hbs` to `/src/templates/partials/pagination.hbs`. 

That should fix the problem.

**Comment by neilberry** [comment]
Awesome, that works! Thanks :)
