### ISSUE TITLE
Pagination Older & Newer always show hyperlink

### ISSUE THREAD

**Issue by neilberry** [ducksoupdev/gulp-site-generator#7]
Pagination works great but see screenshot below, the conditional statements you have in pagination.hbs don't seem to be working. ie it always shows Older & Newer as hyperlinks even if there aren't any previous or next items to show. 

Maybe grey them out or don't show if this scenario occurs?

![image](https://cloud.githubusercontent.com/assets/1056228/11717230/ff8d5a5a-9f46-11e5-877c-765ad67eb90d.png)

**Comment by ducksoupdev** [comment]
The newer and older links have the class of 'disabled' assigned to them to allow them to be styled according to your theme. The links are not clickable when disabled but remain on the page.

![newer-button-disabled](https://cloud.githubusercontent.com/assets/946879/11839840/d43a72b0-a3e8-11e5-8bc5-916a35397e02.png)

**Comment by neilberry** [comment]
Thanks Matt, that'll work!
