### ISSUE TITLE
Image minification task

### ISSUE THREAD

**Issue by neilberry** [ducksoupdev/gulp-site-generator#9]
Re: the images minification and running gulp develop (the live-reload task), this takes a while to complete (couple of minutes in my case), I guess depending on the size and amount of your images. 

Wonder if it would be more efficient to have a separate task for image minification that only optimises images for production. What do you think?

**Comment by neilberry** [comment]
How do I remove image-min from the gulp task? 

I've tried commenting the code out in /tools/gulp/tasks/image-min.js but I get the following error.

![image](https://cloud.githubusercontent.com/assets/1056228/12071431/4a3646c0-b0a4-11e5-899a-45c84c79f67a.png)

**Comment by ducksoupdev** [comment]
The latest release (0.1.25) contains an update that allows you to add an "imageCompression" property to site.json. If set to false, then it will not compress any images and copy them to your build directory.

**Comment by neilberry** [comment]
Thanks Matt!
